create or replace TRIGGER "HQDB"."TG_UPD_EMP_EMPLOYEE" 
AFTER UPDATE  ON HQDB.EMP_EMPLOYEE
FOR EACH ROW
DECLARE

  V_TRANS_NO NUMBER(15);
  old_desc varchar2(500);
  new_desc varchar2(500);
  lockUser NUMBER(1);
  lockRole NUMBER(1);
BEGIN
  SELECT HQDB.SEQ_UPD_EMP_EMPLOYEE_TRANS_NO.NEXTVAL
      INTO V_TRANS_NO
      FROM DUAL ;
--lockUser  lockRole	0   donot lock , 1 lock when DEPT_FK change , 9 lock when SECT_FK change
  lockUser :=0;
  lockRole :=0;
    IF UPDATING ('EMP_PK') AND :OLD.EMP_PK <> :NEW.EMP_PK THEN
        INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	    (FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
        VALUES
	    ('EMP_PK', :OLD.EMP_PK, :NEW.EMP_PK, 'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
    END IF;

    IF UPDATING ('EMP_NO') AND :OLD.EMP_NO <> :NEW.EMP_NO THEN
        INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	   (FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
        VALUES
	   ('EMP_NO', :OLD.EMP_NO, :NEW.EMP_NO,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
    END IF;

    IF UPDATING ('CLASS_FK') AND :OLD.CLASS_FK <> :NEW.CLASS_FK THEN
        INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	    (FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
        VALUES
	    ('CLASS_FK', :OLD.CLASS_FK, :NEW.CLASS_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );

        SELECT CLASS_DESC INTO old_desc  FROM HQDB.REF_CLASS  WHERE CLASS_PK= :OLD.CLASS_FK;
        SELECT CLASS_DESC INTO new_desc  FROM HQDB.REF_CLASS  WHERE CLASS_PK= :NEW.CLASS_FK;
        INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	    (FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
        VALUES
	    ('CLASS_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
    END IF;

	IF UPDATING ('FULL_NAME') AND :OLD.FULL_NAME <> :NEW.FULL_NAME THEN
         INSERT INTO HQDB.UPD_EMP_EMPLOYEE
        (FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
        VALUES
	    ('FULL_NAME', :OLD.FULL_NAME, :NEW.FULL_NAME,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('ENG_NAME') AND :OLD.ENG_NAME <> :NEW.ENG_NAME THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('ENG_NAME', :OLD.ENG_NAME, :NEW.ENG_NAME,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('TRIBE_DESC_A') AND :OLD.TRIBE_DESC_A <> :NEW.TRIBE_DESC_A THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('TRIBE_DESC_A', :OLD.TRIBE_DESC_A, :NEW.TRIBE_DESC_A,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('TRIBE_DESC_E') AND :OLD.TRIBE_DESC_E <> :NEW.TRIBE_DESC_E THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('TRIBE_DESC_E', :OLD.TRIBE_DESC_E, :NEW.TRIBE_DESC_E,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('HIRE_DATE') AND :OLD.HIRE_DATE <> :NEW.HIRE_DATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('HIRE_DATE', TO_CHAR(:OLD.HIRE_DATE,'YYYY/MM/DD'), TO_CHAR(:NEW.HIRE_DATE,'YYYY/MM/DD'),
	 'DATE', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

     IF UPDATING ('MIL_CARD_EXDATE') AND :OLD.MIL_CARD_EXDATE <> :NEW.MIL_CARD_EXDATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MIL_CARD_EXDATE', TO_CHAR(:OLD.MIL_CARD_EXDATE,'YYYY/MM/DD'), TO_CHAR(:NEW.MIL_CARD_EXDATE,'YYYY/MM/DD'),
	 'DATE', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('JOIN_DATE') AND :OLD.JOIN_DATE <> :NEW.JOIN_DATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('JOIN_DATE', TO_CHAR(:OLD.JOIN_DATE,'YYYY/MM/DD'), TO_CHAR(:NEW.JOIN_DATE,'YYYY/MM/DD'),
	 'DATE', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;



   IF UPDATING ('STATUS_DATE') AND :OLD.STATUS_DATE <> :NEW.STATUS_DATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('STATUS_DATE', TO_CHAR(:OLD.STATUS_DATE,'YYYY/MM/DD'), TO_CHAR(:NEW.STATUS_DATE,'YYYY/MM/DD'),
	 'DATE', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('STATUS_FK') AND :OLD.STATUS_FK <> :NEW.STATUS_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('STATUS_FK', :OLD.STATUS_FK, :NEW.STATUS_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
     SELECT STATUS_DESC  INTO old_desc  FROM HQDB.REF_EMPSTATUS WHERE STATUS_PK= :OLD.STATUS_FK;
     SELECT STATUS_DESC  INTO new_desc  FROM HQDB.REF_EMPSTATUS WHERE STATUS_PK= :NEW.STATUS_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('STATUS_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );

         CASE :NEW.STATUS_FK
            WHEN 30  THEN
     UPDATE HQDB.REF_DEPARTMENT SET MGR_FK=0 WHERE DEPT_PK=:OLD.SECT_FK AND MGR_FK=:OLD.EMP_PK;
     UPDATE HQDB.REF_USER SET ACTIVREC=8 ,    MESSAGE_FK=12 ,USER_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_PK=:OLD.EMP_PK;
     UPDATE HQDB.REF_USER_ROLE SET ACTIVREC=8,MESSAGE_FK=12 ,ROLE_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_FK=:OLD.EMP_PK;
            WHEN 40  THEN
     UPDATE HQDB.REF_DEPARTMENT SET MGR_FK=0 WHERE DEPT_PK=:OLD.SECT_FK AND MGR_FK=:OLD.EMP_PK;
     UPDATE HQDB.REF_USER SET ACTIVREC=8 ,    MESSAGE_FK=12 ,USER_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_PK=:OLD.EMP_PK;
     UPDATE HQDB.REF_USER_ROLE SET ACTIVREC=8,MESSAGE_FK=12 ,ROLE_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_FK=:OLD.EMP_PK;
            WHEN 50  THEN
     UPDATE HQDB.REF_DEPARTMENT SET MGR_FK=0 WHERE DEPT_PK=:OLD.SECT_FK AND MGR_FK=:OLD.EMP_PK;
     UPDATE HQDB.REF_USER SET ACTIVREC=8 ,    MESSAGE_FK=12 ,USER_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_PK=:OLD.EMP_PK;
     UPDATE HQDB.REF_USER_ROLE SET ACTIVREC=8,MESSAGE_FK=12 ,ROLE_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_FK=:OLD.EMP_PK;
            WHEN 90  THEN
     UPDATE HQDB.REF_DEPARTMENT SET MGR_FK=0 WHERE DEPT_PK=:OLD.SECT_FK AND MGR_FK=:OLD.EMP_PK;
     UPDATE HQDB.REF_USER SET ACTIVREC=8 ,    MESSAGE_FK=11 ,USER_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_PK=:OLD.EMP_PK;
     UPDATE HQDB.REF_USER_ROLE SET ACTIVREC=8,MESSAGE_FK=11 ,ROLE_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_FK=:OLD.EMP_PK;
        else
        null;
         END CASE;

	END IF;

   IF UPDATING ('STATUS_DTL') AND :OLD.STATUS_DTL <> :NEW.STATUS_DTL THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('STATUS_DTL', :OLD.STATUS_DTL, :NEW.STATUS_DTL,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

 IF UPDATING ('RANK_FK') AND :OLD.RANK_FK <> :NEW.RANK_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('RANK_FK', :OLD.RANK_FK, :NEW.RANK_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
     SELECT RANK  INTO old_desc  FROM HQDB.REF_RANK WHERE RANK_PK= :OLD.RANK_FK;
     SELECT RANK  INTO new_desc  FROM HQDB.REF_RANK WHERE RANK_PK= :NEW.RANK_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('RANK_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('PRF_FK') AND :OLD.PRF_FK <> :NEW.PRF_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PRF_FK', :OLD.PRF_FK, :NEW.PRF_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	 SELECT PROFESSION  INTO old_desc  FROM HQDB.REF_PROFESSION WHERE PRF_PK= :OLD.PRF_FK;
     SELECT PROFESSION  INTO new_desc  FROM HQDB.REF_PROFESSION WHERE PRF_PK= :NEW.PRF_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PRF_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('DEPT_FK') AND :OLD.DEPT_FK <> :NEW.DEPT_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('DEPT_FK', :OLD.DEPT_FK, :NEW.DEPT_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
     SELECT LONG_SNAME  INTO old_desc  FROM HQDB.REF_DEPARTMENT WHERE DEPT_PK= :OLD.DEPT_FK;
     SELECT LONG_SNAME  INTO new_desc  FROM HQDB.REF_DEPARTMENT WHERE DEPT_PK= :NEW.DEPT_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('DEPT_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
     --   HQDB.EMP_EDIT.SET_BYSECT (:OLD.EMP_PK ,0 , 0 , :OLD.DEPT_FK ,:NEW.DEPT_FK , 1)  ;
     UPDATE HQDB.REF_DEPARTMENT SET MGR_FK=0 WHERE DEPT_PK=:OLD.SECT_FK AND MGR_FK=:OLD.EMP_PK;
	 --lockUser  lockRole	0   donot lock , 1 lock when DEPT_FK change , 9 lock when SECT_FK change
	 IF (lockUser=1) THEN
		UPDATE HQDB.REF_USER SET ACTIVREC=8 ,    MESSAGE_FK=12 ,USER_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_PK=:OLD.EMP_PK;
	 END IF;
     IF (lockRole=1) THEN
		UPDATE HQDB.REF_USER_ROLE SET ACTIVREC=8,MESSAGE_FK=12 ,ROLE_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_FK=:OLD.EMP_PK;
	 END IF;
   END IF;

   IF UPDATING ('SECT_FK') AND :OLD.SECT_FK <> :NEW.SECT_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('SECT_FK', :OLD.SECT_FK, :NEW.SECT_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );

     SELECT LONG_SNAME  INTO old_desc  FROM HQDB.REF_DEPARTMENT WHERE DEPT_PK= :OLD.SECT_FK;
     SELECT LONG_SNAME  INTO new_desc  FROM HQDB.REF_DEPARTMENT WHERE DEPT_PK= :NEW.SECT_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('SECT_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
    --  HQDB.EMP_EDIT.SET_BYSECT (:OLD.EMP_PK ,0 , 0 , :OLD.SECT_FK ,:NEW.SECT_FK , 1)  ;
     UPDATE HQDB.REF_DEPARTMENT SET MGR_FK=0 WHERE DEPT_PK=:OLD.SECT_FK AND MGR_FK=:OLD.EMP_PK;
	 IF (lockUser=9) THEN
		UPDATE HQDB.REF_USER SET ACTIVREC=8 ,    MESSAGE_FK=12 ,USER_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_PK=:OLD.EMP_PK;
	 END IF;
	 IF (lockRole=9) THEN
		UPDATE HQDB.REF_USER_ROLE SET ACTIVREC=8,MESSAGE_FK=12 ,ROLE_TRANS_NO=V_TRANS_NO, NOTES=TO_CHAR(sysdate,'YYYY/MM/DD-HH24:MI') WHERE ACTIVREC=1 AND USER_FK=:OLD.EMP_PK;
	 END IF;
   END IF;

   IF UPDATING ('COUNTRY_FK') AND :OLD.COUNTRY_FK <> :NEW.COUNTRY_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('COUNTRY_FK', :OLD.COUNTRY_FK, :NEW.COUNTRY_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );

     SELECT COUNTRY_AR  INTO old_desc  FROM HQDB.REF_COUNTRY WHERE COUNTRY_PK= :OLD.COUNTRY_FK;
     SELECT COUNTRY_AR  INTO new_desc  FROM HQDB.REF_COUNTRY WHERE COUNTRY_PK= :NEW.COUNTRY_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('COUNTRY_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('COUNTRY_PRV_FK') AND :OLD.COUNTRY_PRV_FK <> :NEW.COUNTRY_PRV_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('COUNTRY_PRV_FK', :OLD.COUNTRY_PRV_FK, :NEW.COUNTRY_PRV_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );

     SELECT COUNTRY_AR  INTO old_desc  FROM HQDB.REF_COUNTRY WHERE COUNTRY_PK= :OLD.COUNTRY_PRV_FK;
     SELECT COUNTRY_AR  INTO new_desc  FROM HQDB.REF_COUNTRY WHERE COUNTRY_PK= :NEW.COUNTRY_PRV_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('COUNTRY_PRV_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('GENDER_FK') AND :OLD.GENDER_FK <> :NEW.GENDER_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('GENDER_FK', :OLD.GENDER_FK, :NEW.GENDER_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
     SELECT GENDER_AR  INTO old_desc  FROM HQDB.REF_GENDER WHERE GENDER_PK= :OLD.GENDER_FK;
     SELECT GENDER_AR  INTO new_desc  FROM HQDB.REF_GENDER WHERE GENDER_PK= :NEW.GENDER_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('GENDER_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('MARITAL_FK') AND :OLD.MARITAL_FK <> :NEW.MARITAL_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MARITAL_FK', :OLD.MARITAL_FK, :NEW.MARITAL_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
     SELECT MARITAL_DESC  INTO old_desc  FROM HQDB.REF_MARITAL WHERE MARITAL_PK= :OLD.MARITAL_FK;
     SELECT MARITAL_DESC  INTO new_desc  FROM HQDB.REF_MARITAL WHERE MARITAL_PK= :NEW.MARITAL_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MARITAL_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('RELEGION_FK') AND :OLD.RELEGION_FK <> :NEW.RELEGION_FK THEN
        INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	    (FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
        VALUES
	    ('RELEGION_FK', :OLD.RELEGION_FK, :NEW.RELEGION_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	 SELECT RELEGION_AR  INTO old_desc  FROM HQDB.REF_RELEGION WHERE RELEGION_PK= :OLD.RELEGION_FK;
     SELECT RELEGION_AR  INTO new_desc  FROM HQDB.REF_RELEGION WHERE RELEGION_PK= :NEW.RELEGION_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('RELEGION_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('BIRTH_DATE') AND :OLD.BIRTH_DATE <> :NEW.BIRTH_DATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('BIRTH_DATE', TO_CHAR(:OLD.BIRTH_DATE,'YYYY/MM/DD'), TO_CHAR(:NEW.BIRTH_DATE,'YYYY/MM/DD'),
	 'DATE', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('BIRTH_PLACE') AND :OLD.BIRTH_PLACE <> :NEW.BIRTH_PLACE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('BIRTH_PLACE', :OLD.BIRTH_PLACE, :NEW.BIRTH_PLACE,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('MOTHER_NAME_A') AND :OLD.MOTHER_NAME_A <> :NEW.MOTHER_NAME_A THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MOTHER_NAME_A', :OLD.MOTHER_NAME_A, :NEW.MOTHER_NAME_A,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('MOTHER_NAME_E') AND :OLD.MOTHER_NAME_E <> :NEW.MOTHER_NAME_E THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MOTHER_NAME_E', :OLD.MOTHER_NAME_E, :NEW.MOTHER_NAME_E,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('DISTRICT_NO') AND :OLD.DISTRICT_NO <> :NEW.DISTRICT_NO THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('DISTRICT_NO', :OLD.DISTRICT_NO, :NEW.DISTRICT_NO,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('DISTRICT_NAME') AND :OLD.DISTRICT_NAME <> :NEW.DISTRICT_NAME THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('DISTRICT_NAME', :OLD.DISTRICT_NAME, :NEW.DISTRICT_NAME,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('NAT_SERVICE_FK') AND :OLD.NAT_SERVICE_FK <> :NEW.NAT_SERVICE_FK THEN
        INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	    (FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
        VALUES
	    ('NAT_SERVICE_FK', :OLD.NAT_SERVICE_FK, :NEW.NAT_SERVICE_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
     SELECT NAT_SERVICE_AR  INTO old_desc  FROM HQDB.REF_NAT_SERVICE WHERE NAT_SERVICE_PK= :OLD.NAT_SERVICE_FK;
     SELECT NAT_SERVICE_AR  INTO new_desc  FROM HQDB.REF_NAT_SERVICE WHERE NAT_SERVICE_PK= :NEW.NAT_SERVICE_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('NAT_SERVICE_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('NAT_SERVICE_GROUP') AND :OLD.NAT_SERVICE_GROUP <> :NEW.NAT_SERVICE_GROUP THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('NAT_SERVICE_GROUP', :OLD.NAT_SERVICE_GROUP, :NEW.NAT_SERVICE_GROUP,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

  IF UPDATING ('QLF_FK') AND :OLD.QLF_FK <> :NEW.QLF_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('QLF_FK', :OLD.QLF_FK, :NEW.QLF_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );

     SELECT QUALIFICATION  INTO old_desc  FROM HQDB.REF_QUALIFICATION WHERE QLF_PK= :OLD.QLF_FK;
     SELECT QUALIFICATION  INTO new_desc  FROM HQDB.REF_QUALIFICATION WHERE QLF_PK= :NEW.QLF_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('QLF_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('QLF_NAME') AND :OLD.QLF_NAME <> :NEW.QLF_NAME THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('QLF_NAME', :OLD.QLF_NAME, :NEW.QLF_NAME,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('QLF_DATE') AND :OLD.QLF_DATE <> :NEW.QLF_DATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('QLF_DATE', TO_CHAR(:OLD.QLF_DATE,'YYYY/MM/DD'), TO_CHAR(:NEW.QLF_DATE,'YYYY/MM/DD'),
	 'DATE', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('QLF_COUNTRY_FK') AND :OLD.QLF_COUNTRY_FK <> :NEW.QLF_COUNTRY_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('QLF_COUNTRY_FK', :OLD.QLF_COUNTRY_FK, :NEW.QLF_COUNTRY_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
    SELECT COUNTRY_AR  INTO old_desc  FROM HQDB.REF_COUNTRY WHERE COUNTRY_PK= :OLD.QLF_COUNTRY_FK;
     SELECT COUNTRY_AR  INTO new_desc  FROM HQDB.REF_COUNTRY WHERE COUNTRY_PK= :NEW.QLF_COUNTRY_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('QLF_COUNTRY_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('QLF_OU_NAME') AND :OLD.QLF_OU_NAME <> :NEW.QLF_OU_NAME THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('QLF_OU_NAME', :OLD.QLF_OU_NAME, :NEW.QLF_OU_NAME,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('CONTRACT_FK') AND :OLD.CONTRACT_FK <> :NEW.CONTRACT_FK THEN
        INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	    (FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
        VALUES
	    ('CONTRACT_FK', :OLD.CONTRACT_FK, :NEW.CONTRACT_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   	SELECT CONTRACT_AR  INTO old_desc  FROM HQDB.REF_CONTRACT WHERE CONTRACT_PK= :OLD.CONTRACT_FK;
    SELECT CONTRACT_AR  INTO new_desc  FROM HQDB.REF_CONTRACT WHERE CONTRACT_PK= :NEW.CONTRACT_FK;
    INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('CONTRACT_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('CONTRACT_OU') AND :OLD.CONTRACT_OU <> :NEW.CONTRACT_OU THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('CONTRACT_OU', :OLD.CONTRACT_OU, :NEW.CONTRACT_OU,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('CONTRACT_PERIOD') AND :OLD.CONTRACT_PERIOD <> :NEW.CONTRACT_PERIOD THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('CONTRACT_PERIOD', :OLD.CONTRACT_PERIOD, :NEW.CONTRACT_PERIOD,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('CONTRACT_END_DATE') AND :OLD.CONTRACT_END_DATE <> :NEW.CONTRACT_END_DATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('CONTRACT_END_DATE', TO_CHAR(:OLD.CONTRACT_END_DATE,'YYYY/MM/DD'), TO_CHAR(:NEW.CONTRACT_END_DATE,'YYYY/MM/DD'),
	 'DATE', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('CONTRACT') AND :OLD.CONTRACT <> :NEW.CONTRACT THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('CONTRACT', :OLD.CONTRACT, :NEW.CONTRACT,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('EIDNO') AND :OLD.EIDNO <> :NEW.EIDNO THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('EIDNO', :OLD.EIDNO, :NEW.EIDNO,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('UIDNO') AND :OLD.UIDNO <> :NEW.UIDNO THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('UIDNO', :OLD.UIDNO, :NEW.UIDNO,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('BLOOD_TYPE_FK') AND :OLD.BLOOD_TYPE_FK <> :NEW.BLOOD_TYPE_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('BLOOD_TYPE_FK', :OLD.BLOOD_TYPE_FK, :NEW.BLOOD_TYPE_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	 SELECT BLOOD_TYPE_AR  INTO old_desc  FROM HQDB.REF_BLOOD_TYPE WHERE BLOOD_TYPE_PK= :OLD.BLOOD_TYPE_FK;
     SELECT BLOOD_TYPE_AR  INTO new_desc  FROM HQDB.REF_BLOOD_TYPE WHERE BLOOD_TYPE_PK= :NEW.BLOOD_TYPE_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('BLOOD_TYPE_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('FAMILY_BOOK') AND :OLD.FAMILY_BOOK <> :NEW.FAMILY_BOOK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('FAMILY_BOOK', :OLD.FAMILY_BOOK, :NEW.FAMILY_BOOK,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('PHONE') AND :OLD.PHONE <> :NEW.PHONE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PHONE', :OLD.PHONE, :NEW.PHONE,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('PHONE2') AND :OLD.PHONE2 <> :NEW.PHONE2 THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PHONE2', :OLD.PHONE2, :NEW.PHONE2,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('PHONE_OFFICE') AND :OLD.PHONE_OFFICE <> :NEW.PHONE_OFFICE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PHONE_OFFICE', :OLD.PHONE_OFFICE, :NEW.PHONE_OFFICE,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('RES_EMIRATE') AND :OLD.RES_EMIRATE <> :NEW.RES_EMIRATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('RES_EMIRATE', :OLD.RES_EMIRATE, :NEW.RES_EMIRATE,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('RES_CITY') AND :OLD.RES_CITY <> :NEW.RES_CITY THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('RES_CITY', :OLD.RES_CITY, :NEW.RES_CITY,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('RES_AREA') AND :OLD.RES_AREA <> :NEW.RES_AREA THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('RES_AREA', :OLD.RES_AREA, :NEW.RES_AREA,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

  IF UPDATING ('EMRG_CALL_NAME') AND :OLD.EMRG_CALL_NAME <> :NEW.EMRG_CALL_NAME THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('EMRG_CALL_NAME', :OLD.EMRG_CALL_NAME, :NEW.EMRG_CALL_NAME,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('EMRG_CALL_PHONE') AND :OLD.EMRG_CALL_PHONE <> :NEW.EMRG_CALL_PHONE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('EMRG_CALL_PHONE', :OLD.EMRG_CALL_PHONE, :NEW.EMRG_CALL_PHONE,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('EMRG_CALL_RELATION') AND :OLD.EMRG_CALL_RELATION <> :NEW.EMRG_CALL_RELATION THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('EMRG_CALL_RELATION', :OLD.EMRG_CALL_RELATION, :NEW.EMRG_CALL_RELATION,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('EMRG_CALL_ADDRESS') AND :OLD.EMRG_CALL_ADDRESS <> :NEW.EMRG_CALL_ADDRESS THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('EMRG_CALL_ADDRESS', :OLD.EMRG_CALL_ADDRESS, :NEW.EMRG_CALL_ADDRESS,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('EMRG_OTHER_CONTACT') AND :OLD.EMRG_OTHER_CONTACT <> :NEW.EMRG_OTHER_CONTACT THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('EMRG_OTHER_CONTACT', :OLD.EMRG_OTHER_CONTACT, :NEW.EMRG_OTHER_CONTACT,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('EMAIL_LAN') AND :OLD.EMAIL_LAN <> :NEW.EMAIL_LAN THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('EMAIL_LAN', :OLD.EMAIL_LAN, :NEW.EMAIL_LAN,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('EMAIL_NET') AND :OLD.EMAIL_NET <> :NEW.EMAIL_NET THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('EMAIL_NET', :OLD.EMAIL_NET, :NEW.EMAIL_NET,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('BBM_PINCODE') AND :OLD.BBM_PINCODE <> :NEW.BBM_PINCODE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('BBM_PINCODE', :OLD.BBM_PINCODE, :NEW.BBM_PINCODE,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

    IF UPDATING ('WORKMODE_FK') AND :OLD.WORKMODE_FK <> :NEW.WORKMODE_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('WORKMODE_FK', :OLD.WORKMODE_FK, :NEW.WORKMODE_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	 SELECT WORKMODE  INTO old_desc  FROM HQDB.REF_WORKMODE WHERE WORKMODE_PK= :OLD.WORKMODE_FK;
     SELECT WORKMODE  INTO new_desc  FROM HQDB.REF_WORKMODE WHERE WORKMODE_PK= :NEW.WORKMODE_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('WORKMODE_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
    END IF;

    IF UPDATING ('WORK_GROUP_FK') AND :OLD.WORK_GROUP_FK <> :NEW.WORK_GROUP_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('WORK_GROUP_FK', :OLD.WORK_GROUP_FK, :NEW.WORK_GROUP_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	 SELECT WORK_GROUP_AR  INTO old_desc  FROM HQDB.REF_WORK_GROUP WHERE WORK_GROUP_PK= :OLD.WORK_GROUP_FK;
     SELECT WORK_GROUP_AR  INTO new_desc  FROM HQDB.REF_WORK_GROUP WHERE WORK_GROUP_PK= :NEW.WORK_GROUP_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('WORK_GROUP_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
    END IF;

   IF UPDATING ('WORK_GROUP') AND :OLD.WORK_GROUP <> :NEW.WORK_GROUP THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('WORK_GROUP', :OLD.WORK_GROUP, :NEW.WORK_GROUP,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('ASSIGNED_JOB') AND :OLD.ASSIGNED_JOB <> :NEW.ASSIGNED_JOB THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('ASSIGNED_JOB', :OLD.ASSIGNED_JOB, :NEW.ASSIGNED_JOB,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('ADDITIONAL_JOB') and :OLD.ADDITIONAL_JOB  <> :NEW.ADDITIONAL_JOB THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('ADDITIONAL_JOB', :OLD.ADDITIONAL_JOB, :NEW.ADDITIONAL_JOB,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

  IF UPDATING ('MIL_WEAR_FK') and :OLD.MIL_WEAR_FK <> :NEW.MIL_WEAR_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MIL_WEAR_FK', :OLD.MIL_WEAR_FK, :NEW.MIL_WEAR_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	SELECT MIL_WEAR_AR  INTO old_desc  FROM HQDB.REF_MIL_WEAR WHERE MIL_WEAR_PK= :OLD.MIL_WEAR_FK;
    SELECT MIL_WEAR_AR  INTO new_desc  FROM HQDB.REF_MIL_WEAR WHERE MIL_WEAR_PK= :NEW.MIL_WEAR_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MIL_WEAR_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('MIL_TRAIN_FK') AND :OLD.MIL_TRAIN_FK <> :NEW.MIL_TRAIN_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MIL_TRAIN_FK', :OLD.MIL_TRAIN_FK, :NEW.MIL_TRAIN_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
    SELECT MIL_TRAIN_AR  INTO old_desc  FROM HQDB.REF_MIL_TRAIN WHERE MIL_TRAIN_PK= :OLD.MIL_TRAIN_FK;
    SELECT MIL_TRAIN_AR  INTO new_desc  FROM HQDB.REF_MIL_TRAIN WHERE MIL_TRAIN_PK= :NEW.MIL_TRAIN_FK;
    INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MIL_TRAIN_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('PRV_SERV_YEAR') AND :OLD.PRV_SERV_YEAR <> :NEW.PRV_SERV_YEAR THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PRV_SERV_YEAR', :OLD.PRV_SERV_YEAR, :NEW.PRV_SERV_YEAR,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

    IF UPDATING ('PRV_SERV_MONTH') AND :OLD.PRV_SERV_MONTH <> :NEW.PRV_SERV_MONTH THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PRV_SERV_MONTH', :OLD.PRV_SERV_MONTH, :NEW.PRV_SERV_MONTH,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('PRV_SERV_DAY') AND :OLD.PRV_SERV_DAY <> :NEW.PRV_SERV_DAY THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PRV_SERV_DAY', :OLD.PRV_SERV_DAY, :NEW.PRV_SERV_DAY,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

    IF UPDATING ('HEALTH_STATUS_FK') AND :OLD.HEALTH_STATUS_FK <> :NEW.HEALTH_STATUS_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('HEALTH_STATUS_FK', :OLD.HEALTH_STATUS_FK, :NEW.HEALTH_STATUS_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	 SELECT HEALTH_STATUS_AR  INTO old_desc  FROM HQDB.REF_HEALTH_STATUS WHERE HEALTH_STATUS_PK= :OLD.HEALTH_STATUS_FK;
     SELECT HEALTH_STATUS_AR  INTO new_desc  FROM HQDB.REF_HEALTH_STATUS WHERE HEALTH_STATUS_PK= :NEW.HEALTH_STATUS_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('HEALTH_STATUS_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('LAST_MEDICAL_TEST_DATE') AND :OLD.LAST_MEDICAL_TEST_DATE <> :NEW.LAST_MEDICAL_TEST_DATE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('LAST_MEDICAL_TEST_DATE', TO_CHAR(:OLD.LAST_MEDICAL_TEST_DATE,'YYYY/MM/DD'), TO_CHAR(:NEW.LAST_MEDICAL_TEST_DATE,'YYYY/MM/DD'),
	 'DATE', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

     IF UPDATING ('PRF_TRAIN_FK') AND :OLD.PRF_TRAIN_FK <> :NEW.PRF_TRAIN_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PRF_TRAIN_FK', :OLD.PRF_TRAIN_FK, :NEW.PRF_TRAIN_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	 SELECT PRF_TRAIN_AR  INTO old_desc  FROM HQDB.REF_PRF_TRAIN WHERE PRF_TRAIN_PK= :OLD.PRF_TRAIN_FK;
     SELECT PRF_TRAIN_AR  INTO new_desc  FROM HQDB.REF_PRF_TRAIN WHERE PRF_TRAIN_PK= :NEW.PRF_TRAIN_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PRF_TRAIN_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

    IF UPDATING ('SPECIAL_NEED_FK') AND :OLD.SPECIAL_NEED_FK <> :NEW.SPECIAL_NEED_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('SPECIAL_NEED_FK', :OLD.SPECIAL_NEED_FK, :NEW.SPECIAL_NEED_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
     SELECT SPECIAL_NEED_AR  INTO old_desc  FROM HQDB.REF_SPECIAL_NEED WHERE SPECIAL_NEED_PK= :OLD.SPECIAL_NEED_FK;
     SELECT SPECIAL_NEED_AR  INTO new_desc  FROM HQDB.REF_SPECIAL_NEED WHERE SPECIAL_NEED_PK= :NEW.SPECIAL_NEED_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('SPECIAL_NEED_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	END IF;

   IF UPDATING ('MGR_NO') AND :OLD.MGR_NO <> :NEW.MGR_NO THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MGR_NO', :OLD.MGR_NO, :NEW.MGR_NO,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('PASSPORT_NO') AND :OLD.PASSPORT_NO <> :NEW.PASSPORT_NO THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PASSPORT_NO', :OLD.PASSPORT_NO, :NEW.PASSPORT_NO,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('MORE_DETAIL') AND :OLD.MORE_DETAIL <> :NEW.MORE_DETAIL THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MORE_DETAIL', :OLD.MORE_DETAIL, :NEW.MORE_DETAIL,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('SIGN_LIST_FK') AND :OLD.SIGN_LIST_FK <> :NEW.SIGN_LIST_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('SIGN_LIST_FK', :OLD.SIGN_LIST_FK, :NEW.SIGN_LIST_FK,'NUMBER', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
--	     SELECT SIGN_LIST_AR  INTO old_desc  FROM HQDB.REF_SIGN_LIST WHERE SIGN_LIST_PK= :OLD.SIGN_LIST_FK;
 --    SELECT SIGN_LIST_AR  INTO new_desc  FROM HQDB.REF_SIGN_LIST WHERE SIGN_LIST_PK= :NEW.SIGN_LIST_FK;
 --    INSERT INTO HQDB.UPD_EMP_EMPLOYEE
--	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
 --        VALUES
--	('SIGN_LIST_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	END IF;

   IF UPDATING ('NOTES') AND :OLD.NOTES <> :NEW.NOTES THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('NOTES', :OLD.NOTES, :NEW.NOTES,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('RELIGION') AND :OLD.RELIGION <> :NEW.RELIGION THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('RELIGION', :OLD.RELIGION, :NEW.RELIGION,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('PRF_TRAIN') THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('PRF_TRAIN', :OLD.PRF_TRAIN, :NEW.PRF_TRAIN,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

   IF UPDATING ('DATA_SOURCE') AND :OLD.DATA_SOURCE <> :NEW.DATA_SOURCE THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('DATA_SOURCE', :OLD.DATA_SOURCE, :NEW.DATA_SOURCE,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;
    IF UPDATING ('HEIGHT') AND :OLD.HEIGHT <> :NEW.HEIGHT THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('HEIGHT', :OLD.HEIGHT, :NEW.HEIGHT,'VARCHAR2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;


IF UPDATING ('WEIGHT') AND :OLD.WEIGHT <> :NEW.WEIGHT THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('WEIGHT', :OLD.WEIGHT, :NEW.WEIGHT,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;




IF UPDATING ('MOI_ACTJOB_FK') AND :OLD.MOI_ACTJOB_FK <> :NEW.MOI_ACTJOB_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MOI_ACTJOB_FK', :OLD.MOI_ACTJOB_FK, :NEW.MOI_ACTJOB_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
	 SELECT MOI_ACTJOBDT_NAME  INTO old_desc  FROM HQDB.REF_MOI_ACT_JOB WHERE MOI_ACTJOB_PK= :OLD.MOI_ACTJOB_FK;
     SELECT MOI_ACTJOBDT_NAME  INTO new_desc  FROM HQDB.REF_MOI_ACT_JOB WHERE MOI_ACTJOB_PK= :NEW.MOI_ACTJOB_FK;
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('MOI_ACTJOB_FK', old_desc, new_desc,'VARCHA2', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;



IF UPDATING ('ASSIGNED_JOB_FK') AND :OLD.ASSIGNED_JOB_FK <> :NEW.ASSIGNED_JOB_FK THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('ASSIGNED_JOB_FK', :OLD.ASSIGNED_JOB_FK, :NEW.ASSIGNED_JOB_FK,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

IF UPDATING ('ASSIGNED_JOB_AR') AND :OLD.ASSIGNED_JOB_AR <> :NEW.ASSIGNED_JOB_AR THEN
     INSERT INTO HQDB.UPD_EMP_EMPLOYEE
	(FIELD_NAME, OLD_VALUE, NEW_VALUE, DATA_TYPE, ROWID_EDITED, EMP_REC_ID, UPDATED_EMP_PK, APP_USER, ORA_USER, AUDIT_DATE , TRANSACTION_NO )
         VALUES
	('ASSIGNED_JOB_AR', :OLD.ASSIGNED_JOB_AR, :NEW.ASSIGNED_JOB_AR,'FK', :OLD.ROWID, :OLD.REC_ID, :OLD.EMP_PK, :NEW.LAST_USER, USER, SYSDATE , V_TRANS_NO );
   END IF;

END;


