export enum ERROR_TYPES {
	API_ERROR = "API_ERROR",
	BAD_REQUEST = "BAD_REQUEST",
	INTERNET_NETWORK_ERROR = "INTERNET_NETWORK_ERROR",
	TIMEOUT = "TIMEOUT",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	GLOBAL_NETWORK_ERROR = "GLOBAL_NETWORK_ERROR",
	GLOBAL_SERVER_ERROR = "GLOBAL_SERVER_ERROR",
	UNAUTHORIZED = "UNAUTHORIZED",
}
